name: Playit RDP Tunnel

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Enable Remote Desktop and Firewall
        shell: pwsh
        run: |
          Write-Host "Enabling Remote Desktop..."
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0

          Write-Host "Disabling NLA..."
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0

          Write-Host "Allowing RDP through firewall..."
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

          Write-Host "Starting Remote Desktop service..."
          Set-Service -Name TermService -StartupType Automatic
          Start-Service -Name TermService

          Write-Host "RDP port check:"
          netstat -an | findstr "3389"

      - name: Download and Run Playit Tunnel
        shell: pwsh
        env:
          PLAYIT_SECRET: "playit-agent:4035da7b9466a450670009405d7f5b0bbd39636b6e08a5128e65183a2c899786"
        run: |
          Write-Host "Downloading Playit..."
          $playitPath = "$env:TEMP\playit.exe"
          Invoke-WebRequest -Uri "https://playit-cloud.github.io/cli.playit.gg/latest/playit-windows-amd64.exe" -OutFile $playitPath

          Write-Host "Starting Playit tunnel..."
          Start-Process -FilePath $playitPath -ArgumentList '--secret', $env:PLAYIT_SECRET -NoNewWindow

          Write-Host "`n============================="
          Write-Host "Use Playit public URL from dashboard to connect"
          Write-Host "Username: RDP"
          Write-Host "Password: Abc12345"
          Write-Host "============================="

      - name: Keep Runner Alive
        shell: pwsh
        run: |
          Write-Host "RDP + Playit running. Keeping session alive..."
          while ($true) { Start-Sleep -Seconds 300 }
