name: RDP - Playit.gg

on:
  workflow_dispatch:

jobs:
  rdp-playit:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Enable Remote Desktop + Disable Firewall
        run: |
          # Enable RDP service
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "SecurityLayer" -Value 0 -Force

          # Disable firewall (to allow external connection)
          netsh advfirewall set allprofiles state off

          # Restart RDP service
          Start-Service TermService

          # Confirm RDP is listening
          netstat -an | find "3389"

      - name: Create RDP User
        run: |
          $password = "Abc12345"
          $securePass = ConvertTo-SecureString $password -AsPlainText -Force

          if (-not (Get-LocalUser -Name "RDP" -ErrorAction SilentlyContinue)) {
              New-LocalUser -Name "RDP" -Password $securePass -AccountNeverExpires
              Add-LocalGroupMember -Group "Administrators" -Member "RDP"
              Add-LocalGroupMember -Group "Remote Desktop Users" -Member "RDP"
          } else {
              Set-LocalUser -Name "RDP" -Password $securePass
          }

          echo "RDP_PASSWORD=$password" >> $env:GITHUB_ENV

      - name: Download Playit.gg Agent
        run: |
          $url = "https://github.com/playit-cloud/playit-agent/releases/download/v0.16.3/playit-windows-x86_64.exe"
          $path = "$env:TEMP\playit.exe"
          Invoke-WebRequest -Uri $url -OutFile $path
          Write-Host "Playit downloaded to: $path"

      - name: Start Playit Tunnel
        env:
          PLAYIT_AUTH_KEY: ${{ secrets.PLAYIT_AUTH_KEY }}
        run: |
          $playitPath = "$env:TEMP\playit.exe"

          Write-Host "Starting Playit Tunnel..."
          Start-Process -FilePath $playitPath -ArgumentList "--secret $env:PLAYIT_AUTH_KEY --local 3389" -NoNewWindow

          Start-Sleep -Seconds 15
          Write-Host "`n============================="
          Write-Host "Use this to connect (from Playit dashboard):"
          Write-Host "RDP user: RDP"
          Write-Host "Password : $env:RDP_PASSWORD"
          Write-Host "============================="

      - name: Keep session alive
        run: |
          while ($true) {
              Write-Host "[$(Get-Date)] RDP active via Playit"
              Start-Sleep -Seconds 300
          }
