name: RDP - Playit.gg

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Enable Remote Desktop
        shell: pwsh
        run: |
          # Enable RDP service and disable authentication requirements
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' `
                           -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
                           -Name "UserAuthentication" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
                           -Name "SecurityLayer" -Value 0 -Force

          # Open firewall for RDP (3389)
          netsh advfirewall firewall delete rule name="RDP-Playit" || Write-Host "No existing rule"
          netsh advfirewall firewall add rule name="RDP-Playit" dir=in action=allow protocol=TCP localport=3389

          # Restart RDP service
          Restart-Service -Name TermService -Force

      - name: Create RDP User
        shell: pwsh
        run: |
          $password = "Abc12345"
          $securePass = ConvertTo-SecureString $password -AsPlainText -Force

          if (-not (Get-LocalUser -Name "RDP" -ErrorAction SilentlyContinue)) {
              New-LocalUser -Name "RDP" -Password $securePass -AccountNeverExpires
              Add-LocalGroupMember -Group "Administrators" -Member "RDP"
              Add-LocalGroupMember -Group "Remote Desktop Users" -Member "RDP"
          } else {
              $user = Get-LocalUser -Name "RDP"
              $user | Set-LocalUser -Password $securePass
          }

          echo "RDP_PASSWORD=$password" >> $env:GITHUB_ENV

      - name: Download Playit.gg
        shell: pwsh
        run: |
          Write-Host "Downloading Playit agent..."
          $url  = "https://github.com/playit-cloud/playit-agent/releases/download/v0.16.3/playit-windows-x86_64.exe"
          $path = "$env:TEMP\playit.exe"
          Invoke-WebRequest -Uri $url -OutFile $path
          Write-Host "Playit downloaded to $path"

      - name: Start Playit Tunnel
        shell: pwsh
        env:
          PLAYIT_AUTH_KEY: ${{ secrets.PLAYIT_AUTH_KEY }}
        run: |
          $playitPath = "$env:TEMP\playit.exe"
          Write-Host "Starting Playit tunnel..."
          Start-Process -FilePath $playitPath -ArgumentList "--secret $env:PLAYIT_AUTH_KEY" -NoNewWindow
          Start-Sleep -Seconds 15
          Write-Host "✅ Playit tunnel started"
          Write-Host "Check your Playit dashboard for the public RDP address."
          Write-Host "Username: RDP"
          Write-Host "Password: $env:RDP_PASSWORD"
          Write-Host "========================================="

      - name: Keep Workflow Alive
        shell: pwsh
        run: |
          while ($true) {
              Write-Host "[$(Get-Date)] Playit Tunnel Active - Press Ctrl+C to stop"
              Start-Sleep -Seconds 300
          }
